CREATE TABLE person (
    id SERIAL PRIMARY KEY,
    username VARCHAR (80) UNIQUE NOT NULL,
    password VARCHAR (1000) NOT NULL
);

CREATE TABLE activity (
	_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar,
	description varchar,
	location int references location(_id)
);


CREATE TABLE person_activity (
  person_id    int REFERENCES person (_id),
  activity_id int REFERENCES activity (_id),
  CONSTRAINT person_activity_id PRIMARY KEY (person_id, activity_id)  
);